# Generated by Django 4.2.6 on 2024-01-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.SmallIntegerField(choices=[(1, 'clothe'), (2, 'shose'), (3, 'home & kichane'), (4, 'electronics'), (5, 'jewellery')], null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
