# Generated by Django 4.2.6 on 2024-01-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_remove_product_category_product_categorys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categorys',
            field=models.SmallIntegerField(choices=[('clothe', ((1, 'men'), (2, 'women'))), ('shose', ((1, 'bata'), (2, 'clt')))], null=True),
        ),
    ]
