# Generated by Django 5.0.1 on 2024-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0004_remove_product_categorys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categlory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_seller.category'),
            preserve_default=False,
        ),
    ]
