# Generated by Django 5.0.1 on 2024-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0007_rename_cdiscription_category_cdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cdescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
