# Generated by Django 5.0.1 on 2024-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(db_index=True, help_text='Category name (case-insensitive)', max_length=200, unique=True),
        ),
    ]
