# Generated by Django 5.0.1 on 2024-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0010_alter_category_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(help_text='Category name (case-insensitive)', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('cname', 'user')},
        ),
    ]
