# Generated by Django 5.0.1 on 2024-01-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0001_initial'),
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buyer.user')),
            ],
        ),
    ]
