# Generated by Django 5.0.1 on 2024-01-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0003_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='p2.jpg', upload_to='images/'),
        ),
    ]
