# Generated by Django 5.0.1 on 2024-01-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buyer', '0005_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
